<a href="https://colab.research.google.com/github/Crimso777/Mercury-Notebooks/blob/Shane/tts_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Instructions:**


1.   Submit both .ipynb and PDF files, No pdf or no .ipynb will get '0'.
2.   Do not ZIP the files and submit, Zip submission will get '0'.
3.   **Similarity score must be less than 15%**

**RUBRIC:**


**TASK 1 :** **10pts full pts | 0pts No pts**

**TASK 2(a,b) :** **10pts full pts | 0pts No Ans**

**Task 3 :** **5pts Full Marks | 0pts No Answer**

**TASK 4 :**   **5pts Full marks | 0pts No Answer**

**TASK 5 :** **10pts full marks | 0pts No Answer**

**TASK 6 :** **10pts full marks | 0pts No Ans**

**TASK 7 :** **5pts full marks | 0pts No Ans**

**TASK 8 :** **5pts full marks | 0pts No Answer**

**TASK 9 :** **15pts full marks | 0pts No Ans**

**TASK 10 :** **15pts full marks | 0pts No Ans**

**TASK 11 :** **10pts full marks | 0pts No Ans**


#**ICE - 08 : Text Classification**

Text classification terminologies:

* **Training:** Set of documents, set of classes (x , y) where documents are hand-labeled or system-generated
* **Inference:** Predict the class that the new document belongs to when a new, unseen document is given


In [ ]:
from gtts import gTTS
import os
text = open("input_text.txt", "r").read().replace("\n", " ") # Open file, store tokens into text variable
language = 'en' # TODO: How do we make it automatically recognize other languages?
tts = gTTS(text)
tts.save('speech.wav') # Save our text into a .wav file which is automatically saved to your Colab session storage
sound_file = 'speech.wav'
Audio(sound_file, autoplay = True) # Play automatically, look into alternatives

In [ ]:
from gtts import gTTS
import os


file = open("input_text.txt", "r").read().replace("\n", " ")
language = 'en'

tts = gTTS(file) #Provide the string to convert to speech
tts.save('speech.wav') #save the string converted to speech as a .wav file
sound_file = 'speech.wav'
Audio(sound_file, autoplay=True) 

## **(Tutorial) Performing Naive Bayes Classification using Scikit-Learn**

In [ ]:
#from IPython.display import HTML, Audio
#from scipy.io.wavfile import read as wav_read
import speech_recognition as sr
import pyttsx3
#import io
#import ffmpeg

# Initialize the recognizer 
r = sr.Recognizer() 
  
# Function to convert text to
# speech
def SpeakText(command):
      
    # Initialize the engine
    engine = pyttsx3.init()
    engine.say(command) 
    engine.runAndWait()
      
      
# Loop infinitely for user to
# speak
  
while(1):    
      
    # Exception handling to handle
    # exceptions at the runtime
    try:
          
        # use the microphone as source for input.
        with sr.Microphone() as source2:
              
            # wait for a second to let the recognizer
            # adjust the energy threshold based on
            # the surrounding noise level 
            r.adjust_for_ambient_noise(source2, duration=0.2)
              
            #listens for the user's input 
            audio2 = r.listen(source2)
              
            # Using google to recognize audio
            MyText = r.recognize_google(audio2)
            MyText = MyText.lower()
  
            print("Did you say ",MyText)
            SpeakText(MyText)
              
    except sr.RequestError as e:
        print("Could not request results; {0}".format(e))
          
    except sr.UnknownValueError:
        print("unknown error occured")

AttributeError: ignored

In [ ]:
print(vectorizer1.get_feature_names_out())    # returns the features extracted from the text (vocabulary)

data.toarray()    # returns encoded representations


['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

A second measure that is commonly used while creating a Bag-of-Words representation is to use information about the ***term frequency***. *Term frequency* (TF) refers to the number of times a term (i.e. a word) is seen in the text.

In [ ]:
# 'binary' parameter when not set indicates the encoding measure is term frequency
vectorizer2 = CountVectorizer()

# again, an example corpus
corpus = [
     'This is the first Document.',
     'This is the second second document.',
     'And the third one is the document.',
     'Is this the first document document document?',
]

# same as before...
data = vectorizer2.fit_transform(corpus)
data


<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [ ]:
print(vectorizer2.get_feature_names_out())

data.toarray()


['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 1, 0, 1, 1, 0, 2, 1, 0],
       [0, 3, 1, 1, 0, 0, 1, 0, 1]])

### **Using Naive Bayes in scikit-learn**

#### **Step 1. Create/Collect the Data**

In [ ]:
# importing an existing dataset from scikit-learn for demonstrating use of Naive Bayes
from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups()


# scikit-learn provides helpful utilities for out-of-the-box datasets
# what are the various categories of documents in the above dataset?
dataset.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [ ]:
# what are the inputs/attributes in the above dataset?
dataset.data      # returns a list

print(f"Number of articles (inputs): {len(dataset.data)}")

Number of articles (inputs): 11314


In [ ]:
# what are the corresponding outputs/targets in the above dataset?
dataset.target      # returns a n-dimensional NumPy array

print(f"Number of targets (outputs): {dataset.target.shape}")

Number of targets (outputs): (11314,)


In [ ]:
# for the demonstration, let's use only a small subset from the 20 categories
categories = ['talk.religion.misc', 'soc.religion.christian', 'sci.space', 'comp.graphics']

# get the training and testing data and have them ready to use later
train_data = fetch_20newsgroups(subset='train', categories=categories)
test_data = fetch_20newsgroups(subset='test', categories=categories)
print(train_data.data[5])

From: dmcgee@uluhe.soest.hawaii.edu (Don McGee)
Subject: Federal Hearing
Originator: dmcgee@uluhe
Organization: School of Ocean and Earth Science and Technology
Distribution: usa
Lines: 10


Fact or rumor....?  Madalyn Murray O'Hare an atheist who eliminated the
use of the bible reading and prayer in public schools 15 years ago is now
going to appear before the FCC with a petition to stop the reading of the
Gospel on the airways of America.  And she is also campaigning to remove
Christmas programs, songs, etc from the public schools.  If it is true
then mail to Federal Communications Commission 1919 H Street Washington DC
20054 expressing your opposition to her request.  Reference Petition number

2493.



#### **Step 2(a): Prepare the inputs for modeling**

In [ ]:
# create BoW representations for the training data (excluding targets); aka feature extraction
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer()

# first, build the training vocabulary, fit()
# then, use the vocabulary to transform the training data into a document-term matrix, transform()
# results in a document-term matrix structure
X_train = bow_vectorizer.fit_transform(train_data.data)

# let's check the document-term matrix
X_train

# convert sparse matrix to dense matrix
# X_train.to_array()

<2153x35329 sparse matrix of type '<class 'numpy.int64'>'
	with 352179 stored elements in Compressed Sparse Row format>

#### **Step 2(b): Prepare the outputs for modeling**

In [ ]:
# store the outputs (corresponding to the news articles in the training set) for easy access
y_train = train_data.target     # returns a n-dimensional NumPy array
y_train

# print(f"y_train array size: {y_train.shape}")

array([2, 2, 1, 2, 0, 3, 1, 0, 3, 3, 2, 0, 1, 2, 3, 2, 2, 0, 1, 0, 1, 0,
       1, 2, 2, 0, 0, 1, 3, 3, 1, 1, 2, 1, 1, 1, 0, 2, 0, 3, 2, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 3, 3, 1, 0, 1, 2, 3, 2, 2, 2, 0, 3, 1, 1, 2, 3,
       0, 2, 0, 0, 1, 0, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 2, 2, 0, 2,
       0, 2, 0, 2, 1, 1, 3, 0, 1, 1, 0, 1, 0, 3, 0, 2, 3, 0, 2, 2, 3, 3,
       1, 3, 2, 1, 0, 2, 0, 1, 2, 0, 2, 3, 0, 1, 2, 2, 1, 2, 2, 1, 3, 2,
       1, 0, 2, 1, 0, 0, 2, 1, 2, 1, 0, 2, 1, 1, 2, 0, 1, 2, 2, 1, 0, 2,
       2, 3, 2, 0, 1, 0, 0, 1, 3, 2, 2, 1, 2, 2, 0, 3, 2, 0, 2, 0, 0, 0,
       2, 0, 0, 2, 0, 2, 3, 2, 2, 0, 3, 1, 1, 1, 1, 1, 1, 3, 1, 0, 2, 3,
       2, 3, 3, 2, 1, 0, 1, 3, 1, 3, 2, 0, 2, 1, 1, 3, 0, 1, 1, 2, 1, 2,
       2, 3, 0, 1, 1, 1, 3, 0, 3, 0, 2, 1, 0, 0, 0, 1, 0, 2, 2, 1, 2, 1,
       2, 0, 3, 1, 1, 1, 1, 1, 2, 2, 3, 3, 2, 1, 0, 2, 0, 0, 2, 3, 0, 2,
       0, 2, 1, 3, 3, 3, 1, 0, 2, 1, 3, 0, 2, 2, 3, 2, 0, 0, 2, 2, 1, 1,
       0, 0, 2, 2, 0, 1, 1, 2, 0, 0, 0, 1, 3, 2, 1,

##### **Transforming the outputs for a supervised learning task**

**PLEASE READ:** Depending on the dataset you are working with, there could be datasets that contain non-numerical labels corresponding to the targets (outputs for a supervised learning problem). scikit-learn also includes utilities that you could use to convert (transform) your non-numeric labels to numeric ones.

In [ ]:
from sklearn import preprocessing
tgt_enc = preprocessing.LabelEncoder()

# assume the following is the list of unique classes in your data
some_data_targets = ["paris", "paris", "tokyo", "amsterdam", "paris", "tokyo", "tokyo", "tokyo", "amsterdam", "england"]

# fit your targets of the training data to the LabelEncoder instance
tgt_enc.fit(some_data_targets)

# get the set of unique classes
print(f"Unique categories: {list(tgt_enc.classes_)}")

# encode the targets as numerical labels
encoded_tgts = tgt_enc.transform(["tokyo", "tokyo", "paris"])
print(f"Encoded labels: {encoded_tgts}")

Unique categories: ['amsterdam', 'england', 'paris', 'tokyo']
Encoded labels: [3 3 2]


#### **Step 3: Building a Learning Model Using Naive Bayes Algorithm**

** **IMPORTANT!** ** - Regardless of the task, when building a learning model, always make sure ONLY the data from training set is used to train the model. ***Testing set MUST NEVER to be used to train/build the model***. Testing set is used only to report the results of your model, which is the last step of the process (after the model is trained and you have found a best model).

**Note:** Building the model is also referred to as training the model.

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb_model = MultinomialNB()
mnb_model.fit(X_train, y_train)

MultinomialNB()

#### **Step 4(a): Make Predictions Using the Trained Model**
**Note:** We are assuming that the above model trained is the best model for the data under consideration. *In reality, decision about the best model is based on performing hyperparameter tuning on a tuning/validation data set*. While hyperparameter tuning is out of scope for this notebook, you can always lookup articles, blog posts about this topic on the World Wide Web.

In [ ]:
# before testing the model, ensure your test data, both inputs and outputs, is ready for use:

# 1. preprocess your testing data into a document-term matrix (using the training vocabulary)
X_test = bow_vectorizer.transform(test_data.data)
X_test

<1432x35329 sparse matrix of type '<class 'numpy.int64'>'
	with 230051 stored elements in Compressed Sparse Row format>

In [ ]:
# 2. store the known outputs corresponding to the articles in the test set
y_test = test_data.target

print(f"y_test array size: {y_test.shape}")

y_test array size: (1432,)


In [ ]:
# finally, apply the model on the test set to make predictions
# in this case, predictions are classification labels
predictions = mnb_model.predict(X_test)

In [ ]:
# using the same model but predictions are probabilities
y_pred_prob = mnb_model.predict_proba(X_test)
print(y_pred_prob)

[[2.75544189e-101 1.35696571e-093 9.04229140e-034 1.00000000e+000]
 [1.00000000e+000 8.11913323e-031 5.82342828e-045 1.00498728e-040]
 [7.23391406e-081 1.00000000e+000 6.57667626e-091 2.33963648e-074]
 [1.00000000e+000 2.06238640e-062 6.13232665e-085 3.97450971e-090]
 [4.78607486e-029 9.99999460e-001 5.40232163e-007 7.64770874e-016]
 [1.97449728e-016 3.80488166e-013 1.00000000e+000 1.31095855e-013]
 [1.00746827e-222 1.00000000e+000 1.75010680e-256 2.36523385e-255]
 [1.24078514e-069 1.00000000e+000 1.14014415e-084 1.21604211e-078]
 [1.00000000e+000 3.13263274e-015 1.72011457e-017 6.44230160e-014]
 [3.39809835e-025 1.00000000e+000 2.57276712e-039 1.83202609e-037]
 [9.21847391e-033 3.74504638e-027 2.58294255e-015 1.00000000e+000]
 [4.44624717e-012 8.12823934e-012 9.99999268e-001 7.32111989e-007]
 [1.15879118e-054 1.88240173e-035 1.20272394e-031 1.00000000e+000]
 [2.98126336e-165 2.98083778e-158 5.95385832e-006 9.99994046e-001]
 [6.53315939e-051 1.25933135e-047 9.99999955e-001 4.51282503e-

#### **Step 4(b): Evaluate the Model**

In [ ]:
# importing the metrics module from sklearn
from sklearn import metrics

# use the accuracy_score metric to calculate accuracy of the model
# you evaluate a model by comparing its predictions against the known outputs of the test set
accuracy = metrics.accuracy_score(y_test, predictions)

In [ ]:
# use the confusion matrix metric to understand the predictive power of the model
print(metrics.confusion_matrix(y_test, predictions))

[[371  11   2   5]
 [ 11 377   5   1]
 [  5   4 379  10]
 [  5  11  49 186]]




---



## **Task: Classifying News Articles using Naive Bayes**

### **TASK1. Create Dataset**

We will be using the modified version of the [BBC news dataset](http://mlg.ucd.ie/files/datasets/bbcsport-fulltext.zip) for this task. The zip file containing the raw data is made available on Canvas. Download the zip file and make sure that the file is available within your notebook session. 

**Instructions:** 
* Read all the .txt files in the bbc-updated.zip file 
* Text files read from the zip file must be stored in a Pandas dataframe along with the category the news article belongs to
  * You can use the subdirectory names while reading the files to store category names as corresponding targets in the dataframe
* The dataframe should consist of two columns: 'Text' and 'Category'. Here, ***Text*** column is an attribute and ***Category*** is the target corresponding to the attribute. 
* Use ```pandas.DataFrame.shape``` to print the size of the dataframe after the dataframe is created (useful in verifying all the text files are read)
* You can also use ```pandas.DataFrame.head(n)``` to view the first 'n' examples in the dataframe (useful for verifying that the raw data has been processed as expected)

In [ ]:
import pandas as pd
import os

df = pd.DataFrame({  'Summary':[], 'Labels':[]})

for root, dirs, filenames in os.walk('bbcsport-fulltext.zip'):#read the folder
    for dir_ in dirs:
       
        content=[]#make the list vriable to append the content 
        labels=[]#append lables of each content here
        folderpath = os.path.join(root, dir_)#we need to acess the files of each categories 
        #thats why we need to join the root path to each cateoris
        try:
            for file in os.listdir(folderpath):
                
                filepath=os.path.join(folderpath, file)#here we are iterating through each txt file 
                if os.path.isfile(filepath):
                    
                    f = open(filepath, "r").read()#read the text file
                    content.append(f)#append the summary of the news by categorywies
                    labels.append(dir_)#append the categories also
                    
            df = pd.concat([df, pd.DataFrame({  'Summary':content, 'Labels':labels})],#concat the both dataset 
                      ignore_index=True)#ignore the index of the files
        except:
            pass

        print('Testing')


**Instructions:**
* Once the dataframe is created, split the data into two sets: (1) train set and (2) test set
* Split 30% of the data as test set
* Use ```sklearn.model_selection.train_test_split()``` for easy splitting of data
    * Set ```random_state``` parameter value to **237** to ensure reproducible results
* Use ```pandas.DataFrame.shape``` to print the sizes of the train and test sets after splitting the data

Reference documentation: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html


In [ ]:
# add your code below this comment



### **2. Feature Extraction (Prepare Inputs)**

**Question 2(a): Given the vocabulary *V*, what is the corresponding BoW representation for sentence *S* using the word absence/presence measure?**

***V: { fishing, likes, at, too, Beth, family, campfire, Adam, beach, the, vacation, lake, enjoys, likes }***

***S: "Adam enjoys fishing at the lake. Beth likes fishing too."***

**Instructions:** This question is to be answered without using any code. **DO NOT** use scikit-learn or other NLP libraries to answer this question.

**Answer for Question 2(a):** Type your answer here!

**Question 2(b): Given the same vocabulary *V*, what is the corresponding BoW representation for sentence *S* using the term frequency measure?**

***V: { fishing, likes, at, too, Beth, family, campfire, Adam, beach, the, vacation, lake, enjoys, likes }***

***S: "Adam enjoys fishing at the lake. Beth likes fishing too."***

**Instructions:** This question is to be answered without using any code and/or scikit-learn. **DO NOT** use scikit-learn or other NLP libraries to answer this question.

**Answer for Question 2(b):** Type your answer here!



---



**Question 3: Given the same vocabulary (as in Questions 2a. and 2b.), write the BoW representations for the following sentence S using both measures (presence/absence of words and term frequency information):**

***S: He wanted to bring peace to his kingdom but his enemies killed him.***

**Instructions:** This question is to be answered without using any code and/or scikit-learn.  **DO NOT** use scikit-learn or other NLP libraries to answer this question.

**Answer for Question 3:** Type your answer here!



---



**Question 4: Consider the following code snippet:**

```
bow_vect = CountVectorizer()

some_corpus = [
     'It is raining heavily today.',
     'And the weather is unpredictable.',
     'Weather forecast for tomorrow says sunny.',
     'Is it raining heavily today?',
]

res_data = bow_vect.fit_transform(some_corpus)

bow_vect.get_feature_names())
>>> ['and', 'for', 'forecast', 'heavily', 'is', 'it', 'raining', 'says', 'sunny', 'the', 'today', 'tomorrow', 'unpredictable', 'weather']


res_data.toarray()
>>> array([ [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0],
            [1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
            [0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1],
            [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0] ])

```

**In the above snippet, '>>>' indicates the output corresponding to the previous line of code. Something interesting is happening after the sentences are converted to their BoW representations. Can you identify? After you identify, provide your observation about what might be impacted/affected when using the encoded representations as shown in the above code snippet.**

**Instructions:** You do not have to run the above code again since the outputs that you would need to answer the corresponding question is already provided.


**Answer for Question 4:** Type your answer here!



---



**Question 5: For the given task, use the term frequency measure to compute the BoW representations for the text documents in the modified version of the BBC dataset.**

**Instructions:** 
* This question is to be answered by using scikit-learn (similar to what was demonstrated in the tutorial section)
* Create BoW representations for train and test sets.

In [ ]:
# add your code below this comment



### **3. Prepare Outputs/Labels**

**Instructions:**
* Check to see how the outputs are in the data
* If categories are non-numeric, then encode them as numeric labels (similar to what was discussed in the tutorial demonstration)
* You will have to perform encoding for targets in both train and test sets
* Make sure to perform the same encoding that was done for the targets in the training set when encoding the targets in the test set.

In [ ]:
# add your code below this comment



### **4. Model Training and Evaluation**

**Question 6: Train a Naive Bayes model using the training set. Once the model is trained, apply the model on the test set and evalaute the performance of the model by calculating accuracy and generating the confusion matrix.**

**Instructions:**
* Again, this section is very similar to what was demonstrated in the tutorial section.
* Create a Multinomial Naive Bayes classifier (model).
* Train the model using the data in the training set.
* Apply the model on the test set data to get the predictions made by the model.
* Once the predictions are generated, use ```sklearn.metrics.accuracy_score()``` and ```sklearn.metrics.confusion_matrix()``` as metrics to report your model performance. 

In [ ]:
# add your code below this comment



### **Establishing a baseline model**

Baseline models are helpful for easy comparison of the models you build. These models are trained using simple heuristics or rules.

**Instructions:**
* All you have to do is run the following block of code. Report the accuracy of your model (the Naive Bayes one) in comparison to the baseline model created in the following code block

In [ ]:
# Baselines are simple heuristics to make predictions for a given task
# just execute this code block; nothing needs to be added/modified
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score
# choose 'most-frequent class' as the baseline method
baseline_model = DummyClassifier(strategy="most_frequent")

# fit the baseline model on the training data
baseline_model.fit(X_train, y_train)

# make predictions on the test data using the created baseline model
baseline_preds = baseline_model.predict(X_test)

# compute the accuracy of the baseline model
print(accuracy_score(y_test, baseline_preds))

0.2779329608938548


**Report the accuracies for the baseline and NB models here. Type your answer below! Indicate clearly the numbers corresponding to the models.**

###Question-7

Explain why Naive Bayes classifiers are not sensitive to irrelevant features?

ANS HERE

###Question-8

Why is naive Bayesian classification called" naive? Briefly outline the major ideas of naive Bayes classification.

ANS HERE

#**Logistic Regression**

Logistic regression is an example of a discriminative classifier and is commonly used in text classification, as a baseline in research, and as an MVP in real-world industry scenarios.



###Question-9
####**Perform text classification using Logistic Regression for same dataset(News articles) used for Naive Bayes and generate confusion matrix**

In [ ]:
#code here

#**Support Vector Machine**
Unlike logistic regression, SVM aims to look for an optimal hyperplane in a higher dimensional space, which can separate the classes in the data by a maximum possible margin. Further, SVMs are capable of learning even non-linear separations between classes, unlike logistic regression. However, they may also take longer to train.

###Question-10
####****Perform text classification using SVM for same dataset(News articles) used for Naive Bayes and generate confusion matrix****

In [ ]:
#Code Here

###Question-11
**Compare your results of Naive Bayes, Logistic regression and SVM. Which one do you think is the best text classifier?**

ANS HERE

# **References**

* D. Greene and P. Cunningham. "Practical Solutions to the Problem of Diagonal Dominance in Kernel Document Clustering", Proc. ICML 2006.
* [Datasets (scikit-learn)](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.datasets)
* [All about Naive Bayes (from a scikit-learn perspective)](https://scikit-learn.org/stable/modules/naive_bayes.html)
* [Multinomial Naive Bayes API](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn-naive-bayes-multinomialnb)
* [Evaluation metrics](https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics)
* [Feature extraction module](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.feature_extraction)
* [Transforming prediction targets using LabelEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)
* [Text classification using different classifiers](https://www.oreilly.com/library/view/practical-natural-language/9781492054047/ch04.html)

